# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2022-08-11 23:20
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
# from django.contrib.postgres.fields import ArrayField
from djongo import models
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('ip_address', models.CharField(max_length=50, verbose_name='Dirección IP')),
                ('port', models.CharField(max_length=5, verbose_name='Puerto')),
                ('MAC_address', models.CharField(error_messages={'unique': 'Ya existe un dispositivo con esa dirección MAC.'}, max_length=50, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^([0-9A-Fa-f]{2}[:-]){5}([0-9A-Fa-f]{2})$', 32), 'Ingrese un documento válido (números únicamente).')], verbose_name='Dirección MAC')),
                ('type', models.CharField(max_length=10, verbose_name='Tipo de dispositivo')),
                ('category_list', models.ManyToManyField('users.Category', blank=True, verbose_name='Categorías'))
            ],
        ),
    ]
