# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2022-08-13 01:58
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='MAC_address',
            field=models.CharField(error_messages={'unique': 'Ya existe un dispositivo con esa dirección MAC.'}, max_length=50, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^([0-9A-Fa-f]{2}[:-]){5}([0-9A-Fa-f]{2})$', 32), 'Ingrese una dirección MAC válida.')], verbose_name='Dirección MAC'),
        ),
        migrations.AlterField(
            model_name='device',
            name='category_list',
            field=models.ManyToManyField(blank=True, max_length=10, related_name='device_category_list', to='users.Category'),
        ),
        migrations.AlterField(
            model_name='device',
            name='ip_address',
            field=models.GenericIPAddressField(verbose_name='Dirección IP'),
        ),
    ]
