# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2022-08-17 02:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_auto_20220816_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='last_ping',
            field=models.DateTimeField(default=None, verbose_name='Fecha y hora de último ping'),
            preserve_default=False,
        ),
    ]
