# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2023-03-19 06:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0005_auto_20220817_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='password',
            field=models.CharField(default='', max_length=50, verbose_name='Password Autenticacion'),
        ),
        migrations.AddField(
            model_name='device',
            name='usuario',
            field=models.CharField(default='', max_length=50, verbose_name='Usuario Autenticacion'),
        ),
        migrations.AlterField(
            model_name='device',
            name='cert',
            field=models.CharField(max_length=4096, verbose_name='Certificado'),
        ),
    ]
