# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2023-03-26 12:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0006_device_cert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='cert',
            field=models.TextField(max_length=4096, verbose_name='Certificado'),
        ),
    ]
