# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2023-03-26 12:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0007_auto_20230326_0924'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='password',
            field=models.CharField(default='', max_length=50, verbose_name='Password Autenticacion'),
        ),
        migrations.AddField(
            model_name='device',
            name='usuario',
            field=models.CharField(default='', max_length=50, verbose_name='Usuario Autenticacion'),
        ),
    ]
