# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2023-03-29 11:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0008_auto_20230326_0932'),
        ('devices', '0006_auto_20230319_0312'),
    ]

    operations = [
    ]
