# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2023-03-29 11:01
from __future__ import unicode_literals

import cryptographic_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0009_merge_20230329_0801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='cert',
            field=models.TextField(max_length=4096, verbose_name='Certificado'),
        ),
        migrations.AlterField(
            model_name='device',
            name='password',
            field=cryptographic_fields.fields.EncryptedCharField(blank=True, default='', verbose_name='Password Autenticacion'),
        ),
    ]
