# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2023-12-12 03:43
from __future__ import unicode_literals

import cryptographic_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0010_auto_20230329_0801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='password',
            field=cryptographic_fields.fields.EncryptedCharField(blank=True, default='', verbose_name='Password Autenticación'),
        ),
        migrations.AlterField(
            model_name='device',
            name='usuario',
            field=models.CharField(default='', max_length=50, verbose_name='Usuario Autenticación'),
        ),
    ]
