# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-13 01:03
from __future__ import unicode_literals
from socketserver import ThreadingUnixDatagramServer

from django.conf import settings
import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import re


class Migration(migrations.Migration):

    initial = ThreadingUnixDatagramServer

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=50, verbose_name='Apellido')),
                ('email', models.EmailField(error_messages={'unique': 'Ya existe un usuario con ese email.'}, max_length=50, unique=True, verbose_name='Email')),
                ('identity', models.CharField(error_messages={'unique': 'Ya existe un usuario con ese DNI.'}, max_length=8, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[0-9]*$'), 'Ingrese un documento v\xe1lido (n\xfameros \xfanicamente).')], verbose_name='DNI')),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(re.compile('^[0-9-]*$'), 'Ingrese un tel\xe9fono v\xe1lido (n\xfameros y guiones \xfanicamente).')], verbose_name='N\xfamero de tel\xe9fono')),
                ('expiration_date', models.DateField(default=django.utils.timezone.now, help_text='Una vez llegado el d\xeda, se da de baja el usuario.', verbose_name='Fecha de finalizaci\xf3n')),
                ('code', models.CharField(default='', max_length=10, validators=[django.core.validators.RegexValidator(re.compile('^[0-9A-Fa-f]*$'), 'C\xf3digo de tarjeta inv\xe1lido (n\xfameros hexadecimales \xfanicamente).')], verbose_name='C\xf3digo')),
                ('is_staff', models.BooleanField(default=False, help_text='Determina si el usuario tiene permisos para administrar el sitio (no posee franjas horarias).', verbose_name='Administrador')),
                ('is_active', models.BooleanField(default=True, help_text='Determina si el usuario puede utilizar el sistema o no.', verbose_name='Activo')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha y hora de registro')),
            ],
            options={
                'ordering': ['-date_joined'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='TimeZone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_name', models.CharField(max_length=20, verbose_name='Turno')),
                ('begin', models.TimeField(verbose_name='Hora de inicio')),
                ('end', models.TimeField(verbose_name='Hora de finalizaci\xf3n')),
            ],
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='visitor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='friday',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='friday', to='users.TimeZone', verbose_name='Viernes'),
        ),
        migrations.AddField(
            model_name='user',
            name='monday',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='monday', to='users.TimeZone', verbose_name='Lunes'),
        ),
        migrations.AddField(
            model_name='user',
            name='saturday',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='saturday', to='users.TimeZone', verbose_name='S\xe1bado'),
        ),
        migrations.AddField(
            model_name='user',
            name='sunday',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='sunday', to='users.TimeZone', verbose_name='Domingo'),
        ),
        migrations.AddField(
            model_name='user',
            name='thursday',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='thursday', to='users.TimeZone', verbose_name='Jueves'),
        ),
        migrations.AddField(
            model_name='user',
            name='tuesday',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='tuedsay', to='users.TimeZone', verbose_name='Martes'),
        ),
        migrations.AddField(
            model_name='user',
            name='wednesday',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='wendesday', to='users.TimeZone', verbose_name='Mi\xe9rcoles'),
        ),
    ]
