# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2022-08-13 01:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(max_length=20, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='user',
            name='category_list',
            field=models.ManyToManyField(related_name='user_category_list', to='users.Category', verbose_name='Categoria'),
        ),
    ]
