# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2022-09-24 17:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20220919_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movement',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.Device'),
        ),
        migrations.AlterField(
            model_name='movement',
            name='image',
            field=models.FileField(upload_to='', verbose_name='Imagen'),
        ),
    ]
